import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiGo,
  SiDocker,
  SiPostgresql,
  SiApollographql,
  SiGraphql,
  SiMaterialui,
  SiRedux,
} from "react-icons/si";

export const projectList = [
  {
    id: 1,
    dev: "backend",
    title: "Advanced Tracker Calories API",
    desc: "RESTful API for Track Calories using Harrist-Bennedict Equation, Clean Architecture & ORM",
    stack: [
      <SiGo className="stack-icon" />,
      <SiDocker className="stack-icon" />,
      <SiPostgresql className="stack-icon" />,
    ],
    emot: "🍕",
    url: "https://github.com/adityahimaone/daily-tracker-calories-api",
  },
  {
    id: 2,
    dev: "frontend",
    title: "Simple Calories Tracker APP",
    desc: "A simple calories tracker using ReactJS & Graphql",
    stack: [
      <SiReact className="stack-icon" />,
      <SiApollographql className="stack-icon" />,
      <SiGraphql className="stack-icon" />,
      <SiTailwindcss className="stack-icon" />,
      <SiRedux className="stack-icon" />,
    ],
    emot: "🍔",
    url: "https://github.com/adityahimaone/FE-CaloriesTracker",
  },
  {
    id: 3,
    dev: "frontend",
    title: "Hospital Management System",
    desc: "Application for Manage Hospital such as Booking, Management Employee, Management Schedule, & Management Patient",
    stack: [
      <SiReact className="stack-icon" />,
      <SiMaterialui className="stack-icon" />,
      <SiTailwindcss className="stack-icon" />,
      <SiRedux className="stack-icon" />,
    ],
    emot: "🏥",
    url: "https://github.com/adityahimaone/FE-Hospital-Management-System",
  },
  {
    id: 4,
    dev: "frontend",
    title: "Daily Calories APP",
    desc: "Application for Tracking, Count Calories Food Consumed Every Day & Meal Plans integrate with Open API",
    stack: [
      <SiNextdotjs className="stack-icon" />,
      <SiTailwindcss className="stack-icon" />,
      <SiMaterialui className="stack-icon" />,
      <SiRedux className="stack-icon" />,
    ],
    emot: "🍴",
    url: "https://github.com/adityahimaone/Daily-Calorie-Apps",
  },
  {
    id: 5,
    dev: "frontend",
    title: "Car Rental",
    desc: "Application for Booking Car",
    stack: [
      <SiNextdotjs className="stack-icon" />,
      <SiTailwindcss className="stack-icon" />,
      <SiMaterialui className="stack-icon" />,
      <SiRedux className="stack-icon" />,
    ],
    emot: "🚗",
    url: "https://github.com/adityahimaone/next-data-media-handling",
  },
];
